facebook:
  app_id: "REPLACE_APP_ID"
  app_secret: "REPLACE_APP_SECRET"
  scope: "SET SCOPE" # user permission
    
twitter:
  consumer_key: "ZcJf5Fqspqbq2H26FCvng"
  consumer_secret: "mecHswDjQ55urZJOWQFHJ9Z7rntVIa5GRRE7CINWkhE"
